# -*- coding: utf-8 -*-
"""Neural_Network_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wzHa2BwSAWwGf57FFJcjPWDzAYqE24W

Трансформационная свёрточная нейронная сеть

Задача: стилизация изображений (Neural Style Transfer)

База данных: аниме стиль, Kaggle

#Загрузка данных
"""







"""#Предобработка данных"""







"""#Создание и обучение нейронной сети"""













"""#Тестирование нейронной сети"""





